project:
  type: website
  resources:
    - cv.pdf
website:
  title: "Jaume Amores"
  description: "Personal page"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@JaumeEire"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Posts"
        file: posts.qmd
      - text: "Papers"
        url: "papers.pdf"
  page-footer:
    left: "© Copyright 2023 Jaume Amores."
format:
  html:
    theme: [cosmo, _variables.scss]
    css: styles.css
comments:
  giscus:
    repo: beatrizmilz/blog-en
