---
title: "Agency and gratitude"
author: "Jaume Amores"
date: 2023-03-04
toc: true
categories:
  - Health
---

<span style="color:orange">**Note: this post is just a draft in progress. As of now, it consists of a collection of random notes.**</span>

I would like to start contributing following the framework from [Dr. Paul Conti](https://drpaulconti.com/). The basic idea is to do things that make me feel good and can help other people at the same time. This can be small things as:

- Commenting on interesting reads.
- Contributing to open source: my personal project [nbmodular](https://github.com/JaumeAmoresDS/nbmodular), exercism, clojure data science community, and others.
- Do clojure pipeline ala dsblocks.
- Reach out to people that are influencing me and ask them questions that may be of interest to others as well, e.g., in twitter, youtube, etc. Examples: David Sinclair, Andrew Huberman, and Peter Attia. 

Huberman: difficult task after tenacy task. Did they try to wait until drive/motivation/dopamine comes back to baseline (from the experimented valley)? Are the results as strong in that case? Idea basically is to separate the experiments for long time.

Sinclair: some of the suggested strategies require a lot of will power and tenacity. Do you know of mental strategies that can help us achieve those goals? Tricks such as drinking tea or coffee can be quite effective, but I wonder about strategies focused on dieting, which involve a large amount of tenacity.

Fast.ai: nbdev_export done, link to test tutorials, include examples / demos.

Finish tenacity podcast and maybe re-listen
Paul Conti podcasts
book

For each X personal things, do one thing that may help (even just a bit) to the community. 
- Can be for my son
- for others
Try to find best strategy here, something that makes me feel good and works.

Potential next project.

- Learn R language.
- Applied Statistics for Data Science: null hypothesis tests, etc.
- Visualization techniques and libraries: blogs, kaggle notebooks, other material.       
   - Reveal.js / quarto notebooks.
- Papers discussed by Huberman, Attia and maybe Sinclair: analyze them from an statistics point of view and write a blog summarizing the findings. Have a list of blogs about this subject.
   - Potential pitfalls, which ones are stronger from a statistics viewpoint.
   - Do rating. Can even be a website with ratings / open review about this type of papers, automatic review that includes ChatGPT type of analysis, etc. With the AI piece we may be able to automatically find sources references and more context information (opinions, rebuttals, etc.) for these papers.
- Find kaggle projects, mostly focused on medicine, that can be good to participate in.
  - Also for Kaggle Days and social interaction.

- Commit myself to write a blog or something everytime I learn something, e.g., TIL like [Simon Willison](https://til.simonwillison.net/) - see [his github's TIL](https://github.com/simonw/til)





