---
title: "Tenacity and will power"
subtitle: "Potential strategies"
author: "Jaume Amores"
date: 2023-03-04
toc: true
categories:
  - Health
---

<span style="color:orange">**Note: this post is just a draft in progress. As of now, it consists of a collection of random notes.**</span>

## Introduction

This post is just a series of short notes I wrote for myself, on general strategies to achieve tenacity / will power goals.

## Strategies

These are the (evolving) strategies I would like to follow:

- Clearly write goal objectives before trying. Dieting example: always write I will be eating that day,before eating. This is what I can eat today: menu with 2000 calories for example, 30% fat, 25% protein, 10% sugar.

    - Write down times: time when I start breakfast, and duration (end time). Time when I start lunch (if I do it), and duration (end time). Total eating window time (end lunch - beginning breakfast). It should always be lower than 8 hours. No snacks in between.
    - Write down all the coffees and teas, and their times.
    - Extra: may be also the regular drinks (e.g., water), to see how this affects sleep.
    - At least something at coarse level, that has just a reasonable accuracy.
    
- Dieting or other goals: Always write down what I have eaten (or whatever the goal was). That's even more important than meeting objectives. I need to know, if I don't meet them, why I haven't and what could've done better or changed for meeting them. Write this down as well, every time.
    - About writing down what I eat, it doesn't need to be super-accurate. But at least something at coarse level, that has just a reasonable accuracy.

- Sleep objectives. If I don't meet them, what should I've done better, what subset of objectives (e.g., number of coffees) I didn't meet and which strategies I could've followed to meet them. Always have empathy and kindness towards myself, not be harsh, but do not stop trying.

- Buy all the necessary wearables: sleep, glucose, lactose and maybe heart rate (because of its relantionship with will power).

- Continue reading, for instance papers about super-agers and how they get will power. Write down a blog summarizing my findings. 

- Izan:
    - write down notes from Anita and publish them.
    - look for strategies on savings, and publish them.