---
title: "Early childhood education"
author: "Jaume Amores"
date: 2023-03-05
toc: true
categories:
  - Education
---

This is currently a placeholder. The intend of this post is to provide a brief summary about my ongoing research in the world of early childhood education.

## Resources

I list here the books, blogs, and podcasts from which the ideas summarized in this post have been gathered.

### Books

#### Read
- The Whole-Brain Child: 12 Revolutionary Strategies to Nurture Your Child’s Developing Mind by Daniel J. Siegel and Tina Payne Bryson
- Brain Rules for Baby (Updated and Expanded): How to Raise a Smart and Happy Baby Child from Zero to Five by John Medina
- How Children Succeed: Grit, Curiosity, and the Hidden Power of Character by Paul Tough
- How to Talk So Kids Will Listen & Listen So Kids Will Talk by Adele Faber and Elaine Mazlish
- No-Drama Discipline. The Whole-Brain Way to Calm the Chaos and Nurture Your Child's Developing Mind by Daniel J. Siegel and Tina Payne Bryson
- Parenting from the Inside Out. How A Deeper Self-Understanding Can Help You Raise Children Who Thrive by Daniel J. Siegel and Mary Hartzell


#### Want to read
- Tools of the Mind: The Vygotskian Approach to Early Childhood Education (2nd Edition) by elena Bodrova and Deorah J. Leong
- How To Get Kids To Say Yes!: Using the Secret Four Color Languages to Get Kids to Listen by
- Who Am I in the Lives of Children? An Introduction to Early Childhood Education (10th Edition) by Stephanie Feeney and Eva Moravick
- Mind in the Making: The Seven Essential Life Skills Every Child Needs by Ellen Galinsky
- The Complete Resource Book for Preschoolers: Over 2000 Activities and Ideas (Complete Resource Series) by Pam Schiller and Kay Hastings

### Blogs and websites
- [THE 40 BEST BOOKS ON EARLY CHILDHOOD EDUCATION](https://www.early-childhood-education-degrees.com/features/best-books-early-childhood-education/)
- [50 OF THE BEST BOOKS FOR PARENTS](https://www.early-childhood-education-degrees.com/best-books-for-parents/)