---
title: "Learning visually"
subtitle: Short notes on learning by practice and visualization.
author: "Jaume Amores"
date: 2023-10-27
toc: true
categories:
  - Education & Parenting
---

I recently joined the amazing [exercism](https://exercism.org/) community. Exercism is an online free coding platform that encourages learning programming languages through practice, free mentorship by volunteers, and exposure to similar solutions once our own solution has been submitted and pass the tests. Each exercise comes with associated learning material, which is a concise description of the concepts that are strictly required for attempting the exercise. However, the focus is always to encourage the students through problem solving and autonomously investigating the bits that are required. This follows closely recent research on education and neuro-science.

I would like to share related thoughts on learning through practice, visual learning, and mathematics or related disciplines. The following are just short notes on this matter, that can serve both as a high-level roadmap to a potential long-term project, and contain some references that I would like to keep in mind and expand in the future.

I found exercism to be a nicely designed platform that, being open source, could  be extended to be applied to other domains beyond programming languages, and in particular to math problems. We could then use libraries to describe the problems visually, similar to what [3blue1brown](https://www.3blue1brown.com/) does. By presenting math problems as both visual puzzles, and in its original text form, we can make the problem more appealing, following the the ideas of Jo Boaler, e.g., in [Mathematical mindsets](https://www.youcubed.org/resources/mathematical-mindsets/), and [visual mathematics](https://www.youcubed.org/resource/visual-mathematics/). It would be nice if the student could manipulate the problem visually (i.e., manipulating and transforming the graphical elements with a mouse), and if the problem could be presented not only in 2D but also in 3D (using Virtual Reality, ideally), so that the student is able to also manipulate the objects in a sort-of "physical" world (be it through a game that emulates this world, or through gadgets like glasses and gloves, to have a better sensorial experience, although this would only be accessible by people able to buy those gadgets, unfortunately).

[Michael Nielsen](https://michaelnielsen.org/) has written very nice essays on these lines, under the title "Tools for Thought". In particular, his essays [Toward an exploratory medium for mathematics](https://cognitivemedium.com/emm/emm.html), [Thought as a Technology](http://cognitivemedium.com/tat/index.html), and [How can we develop transformative tools for thought?](https://numinous.productions/ttft/) and [Reinventing Explanation](http://michaelnielsen.org/reinventing_explanation/index.html). Similar ideas are recently being developed by many scientists and educators and put in practice in journals such as [Distill](https://distill.pub/). I will be including those references in here as I find them, with a brief description, to serve as sources for the future.
