---
title: "Project-driven learning"
author: "Jaume Amores"
date: 2023-03-05
toc: true
categories:
  - Parenting & Education
---

<span style="color:orange">**Note: this post is, at this moment, just a draft in progress.**</span>

The idea of writing this post came initially as a sort-of response / contribution to the excellent essay from Daniel Higginbotham entitled [Techniques for Efficiently Learning Programming Languages](https://www.flyingmachinestudios.com/programming/learn-programming-languages-efficiently/). Despite the title of the essay, the ideas inside are very much generic for learning to learn basically anything. I will be adding a slighly new perspective which incorporates what I call as a "project-based" approach to learning. This idea is not novel, and can be applied either in conjunction or as an alternative to the ideas expressed in post by D. Higginbotham, depending on what our final goals are. I will also use ideas such as `Exploration` vs `Exploitation` from the field of Reinforcement Learning, which I will be explaning for anyone not familiar in this field.

The gist of project-based learning is to focus our learning journey on those things that will prove to be important in our daily practice or life in general. It is motivated in part by the fact that, many times, when we learn a new field, e.g., in college, we study many concepts that we will never be using or needing in anyway, and end up completely forgotten. To be more concrete, let us take the field of mathematics as an example. 

Given the vast amount of things that are actually interesting and relevant for our lives, this approach can be considered sub-optimal in many cases, making us waste a lot of time on topics that are not even connected to those parts that are relevant to us. Having said that, as I explore in this post, it all depends on what the final goal in our learning adventure. For this, I will be using a framework based on the Exploration vs Exploitation trade-off from Reinforcement Learning.

The gist of it is that, many times, when we start a learning 