---
title: "Resources on Parenting & Early Childhood Education"
author: "Jaume Amores"
date: 2023-03-05
toc: true
categories:
  - Parenting & Education
---

<span style="color:orange">**Note: this post is just a draft in progress. As of now, it consists of a collection of random notes.**</span>

The following provides a compact listing about resources and material I found interesting, on both parenting and early childhood education. This includes books, blogs, and podcasts. The intent is to make use of those resources, plus notes collectedfrom our parenting coach, as a source of material for subsequent posts on the topic of parenting and early childhood education. Some of the books are still in my to-read list, which I indicate by an un-checked box. Books in the "in-progress" list are colored in purple, and they are left unchecked if I read just a few chapters.


## Parenting

### Books
- [x] The Whole-Brain Child: 12 Revolutionary Strategies to Nurture Your Child’s Developing Mind by Daniel J. Siegel and Tina Payne Bryson
- [x] Brain Rules for Baby (Updated and Expanded): How to Raise a Smart and Happy Baby Child from Zero to Five by John Medina
- [x] How Children Succeed: Grit, Curiosity, and the Hidden Power of Character by Paul Tough
- [ ] <span style="color:purple">How to Talk So Kids Will Listen & Listen So Kids Will Talk by Adele Faber and Elaine Mazlish</span>
- [x] No-Drama Discipline. The Whole-Brain Way to Calm the Chaos and Nurture Your Child's Developing Mind by Daniel J. Siegel and Tina Payne Bryson
- [x] Parenting from the Inside Out. How A Deeper Self-Understanding Can Help You Raise Children Who Thrive by Daniel J. Siegel and Mary Hartzell
- [ ] How To Get Kids To Say Yes!: Using the Secret Four Color Languages to Get Kids to Listen by

### Blogs and websites
- [50 OF THE BEST BOOKS FOR PARENTS](https://www.early-childhood-education-degrees.com/best-books-for-parents/)
- [Pathways](https://pathways.org/)
- [Resources from Erikson Institute](https://www.erikson.edu/services/center-children-families/)


## Early Childhood Education

### Books
- [x] <span style="color:purple">Where’s the Math? Books, Games, and Routines to Spark Children’s Thinking</span>
- [ ] Tools of the Mind: The Vygotskian Approach to Early Childhood Education (2nd Edition) by elena Bodrova and Deorah J. Leong
- [ ] Who Am I in the Lives of Children? An Introduction to Early Childhood Education (10th Edition) by Stephanie Feeney and Eva Moravick
- [ ] Mind in the Making: The Seven Essential Life Skills Every Child Needs by Ellen Galinsky
- [ ] The Complete Resource Book for Preschoolers: Over 2000 Activities and Ideas (Complete Resource Series) by Pam Schiller and Kay Hastings

### Blogs and websites
- [Early Math Collaborative from Erikson Institute](https://earlymath.erikson.edu/)
- [THE 40 BEST BOOKS ON EARLY CHILDHOOD EDUCATION](https://www.early-childhood-education-degrees.com/features/best-books-early-childhood-education/)

## General Education

### Math Education

#### Books

- [ ] <span style="color:purple">How I Wish I'd Taught Maths: Lessons learned from research, conversations with experts, and 12 years of mistakes: Reflections on research, conversations with experts, and 12 years of mistakes.</span>
- [ ] <span style="color:purple">Mathematics for human flourishing</span>
- [ ] <span style="color:purple">Mathematical mindsets</span>
- [ ] <span style="color:purple">Change Is the Only Constant: The Wisdom of Calculus in a Madcap World</span>
- [ ] Math with bad drawings

#### Blogs and websites

- [3Blue1Brown](https://www.3blue1brown.com/)

## Learning to learn

### Books

- [ ] Make It Stick: The Science of Successful Learning by Henry L. Roediger III, Mark A. McDaniel, Peter C. Brown

### Blogs and websites

- [Techniques for Efficiently Learning Programming Languages](https://www.flyingmachinestudios.com/programming/learn-programming-languages-efficiently/). Despite the title, this post provides many useful tips 
for learning to learn in general.
- [Recommendations about how to learn mathematics in an enjoyable way](https://www.3blue1brown.com/blog/recommendations#practice)